Style branch
metracul/AndroidCook pull request #1
Opened 2024-08-29 16:43 UTC by metracul

2024-08-29 23:15 UTC, ievetrovdev commented
Название пулл реквеста и ветки не соответствует принятому у нас гит флоу, который мы проходим на онбординге и в рамках котлин спринт. Префикс в сообщении коммита вижу, но в названии ветки и ПР ориентироваться будет сложно, рекомендую пересмотреть гайд

<img width="661" alt="Снимок экрана 2024-08-30 в 02 14 12" src="https://github.com/user-attachments/assets/7513dbad-4d6c-4716-8078-71d281e6e381">

2024-08-29 23:29 UTC, ievetrovdev requested changes
Про гит-флоу актуально - нужно отредактировать согласно первому комменту

2024-08-29 23:29 UTC, ievetrovdev commented on app/src/main/res/layout/activity_second.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
этого макета нет в ТЗ

2024-08-29 23:29 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            />
Рекомендую применять автоформатирование перед коммитом

2024-08-29 23:29 UTC, ievetrovdev commented on app/src/main/java/com/example/androidcook/MainActivity.kt
> +        // Здесь вы можете добавить любую дополнительную настройку UI через binding
кто мы?

2024-08-29 23:29 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +// че за основной отступ...
?

2024-08-29 23:29 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="backMain">#F4FAFF</color>
Пересмотри еще раз серию уроков про стили и ресурсы и обрати внимание на стиль именования значений

2024-08-29 23:29 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">14sp</item> <!-- Размер текста -->
Все значения не забываем выносить в ресурсы и переиспользовать. Размеры элементов/шрифтов, цвета, строки

2024-08-29 23:29 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="cornerRadius">8dp</item>
Все значения не забываем выносить в ресурсы и переиспользовать. Размеры элементов/шрифтов, цвета, строки

2024-08-29 23:29 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        <!-- Вторая кнопка -->
Эти комментарии тебе точно нужны чтобы не запутаться?

2024-08-29 23:29 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +
пустая строка

2024-08-29 23:29 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:paddingHorizontal="16dp"
Как правило в макетах есть самые популярные размеры, которых подавляющее большинство в макете. Их интуитивно можно увидеть и выделить в отдельный ресурс. Например, у нас очень часто встречается расстояние 16dp по бокам экрана или между карточек. Так вот этот размер можно назвать main_space_16. А половину от него, например, так main_space_half_8. Это будет красиво и единообразно.

2024-08-29 23:29 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:paddingHorizontal="16dp"
Стиль названия ресурсов в приложении обычно скорее придумывается, чем берется како-либо эталонный стиль. Существуют разные подходы.

Можно в названии писать цифру в конце, которая означает размер, а можно использовать такую структуру, например:
margin_small_x">10dp
margin_small_xx">12dp 
margin_small_xxx">14dp
margin_normal">16dp
margin_normal_x">18dp
margin_normal_xx">20dp
margin_normal_xxx">22dp

2024-08-29 23:29 UTC, ievetrovdev commented on app/src/main/java/com/example/androidcook/MainActivity.kt
>          enableEdgeToEdge()
Давай уберем enableEdgeToEdge(), чтобы контент активити (и фрагмента) не заезжал на статусбар и навбар.

2024-08-29 23:29 UTC, ievetrovdev commented on app/src/main/java/com/example/androidcook/MainActivity.kt
> +    private lateinit var binding: ActivityMainBinding
lateinit - заманчивая конструкция, но опасная и никак не спасающая от NullPointerException. Вот тут Кирилл Розов наглядно объясняет почему лучше избежать использования lateinit по возможности. https://youtu.be/0nXXUzMyF8c

Лучше стараться продумать подходящее поведение по-умолчанию. В уроке я реализовывал backing property (резервное свойство). Но здесь предлагаю применить более элегантный вариант с помощью делегата lazy, который использует ленивую инициализацию. Это такой механизм, который в лямбде принимает в нашем случае inflate() и возвращает созданный объект, который будет создан при первом обращении к нему.

2024-08-29 23:29 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="btntext">#FFFFFF</color>
Повторять значения одних и тех же цветов с разными айдишниками не рекомендуется. Пусть в ресурсах хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-08-29 23:29 UTC, ievetrovdev commented on app/build.gradle.kts
> +        viewBinding=true
форматирование (обосабливание пробелами)

2024-08-30 12:25 UTC, metracul commented on app/src/main/res/values/dimens.xml
> +// че за основной отступ...
а, я вот этого просто не понял "Размеры основного отступа и половины от основного отступа (в ресурсный файл dimens.xml)."

2024-08-31 08:41 UTC, metracul commented on app/src/main/res/layout/activity_main.xml
> +        <!-- Вторая кнопка -->
убрал

2024-08-31 20:12 UTC, ievetrovdev requested changes
Про нейминг ветки и пулл реквеста писал выше - нужно исправить

2024-08-31 20:12 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="my_light_primary">#f4faff</color>
Смешивать стили именования нельзя. Либо верблюд, либо змея)

2024-08-31 20:12 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="button1">#525DC0</color>
С неймингом до сих пор большие проблемы. Когда у тебя в проекте будет 10 кнопок, то все их будешь запоминать по цифрам? Указывай, к какой конкретно кнопке пренадлежит, например  button_category

2024-08-31 20:12 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="btntext">#FFFFFF</color>
дублирует ресурс `<color name="white">`

2024-08-31 20:12 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_marginStart="4dp"
Все значения не забываем выносить в ресурсы и переиспользовать. Размеры элементов/шрифтов, цвета, строки

2024-08-31 20:12 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            app:iconPadding="4dp"
вынести в ресурсы

2024-08-31 20:12 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            app:iconSize="24dp" />
вынести в ресурсы

2024-08-31 20:12 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="textBtn1">Категории</string>
здесь тоже сделай более понятный нейминг, чтоб другие разработчики потом могли понять, что к чему пренадлежит

2024-08-31 21:08 UTC, closed without merging

2024-09-01 13:09 UTC, ievetrovdev commented
ПР закрыт, пришли плз актуальный на проверку

Если что можно переименовывать ветку тоже. Для этого локально в студии ее изменяешь, затем жмешь ПКМ и выбираешь push